// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v3.21.12
// source: it/v1/category.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCategoryGetCategoryAll = "/it.v1.Category/GetCategoryAll"

type CategoryHTTPServer interface {
	GetCategoryAll(context.Context, *GetCateAllRequest) (*GetCateAllReply, error)
}

func RegisterCategoryHTTPServer(s *http.Server, srv CategoryHTTPServer) {
	r := s.Route("/")
	r.GET("/category/all", _Category_GetCategoryAll0_HTTP_Handler(srv))
}

func _Category_GetCategoryAll0_HTTP_Handler(srv CategoryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCateAllRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCategoryGetCategoryAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCategoryAll(ctx, req.(*GetCateAllRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCateAllReply)
		return ctx.Result(200, reply)
	}
}

type CategoryHTTPClient interface {
	GetCategoryAll(ctx context.Context, req *GetCateAllRequest, opts ...http.CallOption) (rsp *GetCateAllReply, err error)
}

type CategoryHTTPClientImpl struct {
	cc *http.Client
}

func NewCategoryHTTPClient(client *http.Client) CategoryHTTPClient {
	return &CategoryHTTPClientImpl{client}
}

func (c *CategoryHTTPClientImpl) GetCategoryAll(ctx context.Context, in *GetCateAllRequest, opts ...http.CallOption) (*GetCateAllReply, error) {
	var out GetCateAllReply
	pattern := "/category/all"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCategoryGetCategoryAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
